version: '3'
services:
  redis:
    container_name: "redis"
    image: 'redis:6.0'
    env_file: 
      - .env
  postgres:
    container_name: "postgres"
    image: 'postgres:12'
    env_file:
      - .env
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: "-p ${POSTGRES_PORT}"
  gsn-api:
    container_name: "gsn-api"
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: .
    restart: always
    volumes:
      - .:/home/gsn-api
    tty: true
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "9229:9229"
